PAP8908R1 工程代码

set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]

set_property PACKAGE_PIN U18 [get_ports sys_clk]
set_property PACKAGE_PIN N16 [get_ports sys_rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports {ad_porta_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_porta_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_porta_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_porta_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_porta_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_porta_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_porta_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_porta_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_porta_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_porta_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_porta_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_porta_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_porta_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_porta_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_portb_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_portb_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_portb_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_portb_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_portb_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_portb_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_portb_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_portb_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_portb_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_portb_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_portb_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_portb_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_portb_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_portb_data[0]}]
set_property PACKAGE_PIN M14 [get_ports ad_shdnb]
set_property PACKAGE_PIN B20 [get_ports ad_shdna]
set_property PACKAGE_PIN L17 [get_ports ad_porta_clk]
set_property PACKAGE_PIN L16 [get_ports ad_portb_clk]
set_property PACKAGE_PIN K17 [get_ports ad_ofa]
set_property PACKAGE_PIN A20 [get_ports ad_ofb]
set_property PACKAGE_PIN J20 [get_ports {ad_porta_data[13]}]
set_property PACKAGE_PIN H20 [get_ports {ad_porta_data[12]}]
set_property PACKAGE_PIN K19 [get_ports {ad_porta_data[11]}]
set_property PACKAGE_PIN J19 [get_ports {ad_porta_data[10]}]
set_property PACKAGE_PIN G19 [get_ports {ad_porta_data[9]}]
set_property PACKAGE_PIN G20 [get_ports {ad_porta_data[8]}]
set_property PACKAGE_PIN J18 [get_ports {ad_porta_data[7]}]
set_property PACKAGE_PIN H18 [get_ports {ad_porta_data[6]}]
set_property PACKAGE_PIN M20 [get_ports {ad_porta_data[5]}]
set_property PACKAGE_PIN M19 [get_ports {ad_porta_data[4]}]
set_property PACKAGE_PIN L19 [get_ports {ad_porta_data[3]}]
set_property PACKAGE_PIN L20 [get_ports {ad_porta_data[2]}]
set_property PACKAGE_PIN M18 [get_ports {ad_porta_data[1]}]
set_property PACKAGE_PIN M17 [get_ports {ad_porta_data[0]}]
set_property PACKAGE_PIN G18 [get_ports {ad_portb_data[13]}]
set_property PACKAGE_PIN G17 [get_ports {ad_portb_data[12]}]
set_property PACKAGE_PIN E19 [get_ports {ad_portb_data[11]}]
set_property PACKAGE_PIN E18 [get_ports {ad_portb_data[10]}]
set_property PACKAGE_PIN F17 [get_ports {ad_portb_data[9]}]
set_property PACKAGE_PIN F16 [get_ports {ad_portb_data[8]}]
set_property PACKAGE_PIN K16 [get_ports {ad_portb_data[7]}]
set_property PACKAGE_PIN L15 [get_ports {ad_portb_data[6]}]
set_property PACKAGE_PIN L14 [get_ports {ad_portb_data[5]}]
set_property PACKAGE_PIN H16 [get_ports {ad_portb_data[4]}]
set_property PACKAGE_PIN G15 [get_ports {ad_portb_data[3]}]
set_property PACKAGE_PIN H15 [get_ports {ad_portb_data[2]}]
set_property PACKAGE_PIN G14 [get_ports {ad_portb_data[1]}]
set_property PACKAGE_PIN J15 [get_ports {ad_portb_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports ad_shdnb]
set_property IOSTANDARD LVCMOS33 [get_ports ad_shdna]
set_property IOSTANDARD LVCMOS33 [get_ports ad_porta_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ad_portb_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ad_ofa]
set_property IOSTANDARD LVCMOS33 [get_ports ad_ofb]

create_clock -period 20.000 -name sys_clk -waveform {0.000 10.000} [get_ports sys_clk]

set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_adda_data[0]}]

set_property PACKAGE_PIN W15 [get_ports {fmc_adda_data[15]}]
set_property PACKAGE_PIN V16 [get_ports {fmc_adda_data[14]}]
set_property PACKAGE_PIN Y17 [get_ports {fmc_adda_data[13]}]
set_property PACKAGE_PIN W20 [get_ports {fmc_adda_data[12]}]
set_property PACKAGE_PIN W19 [get_ports {fmc_adda_data[11]}]
set_property PACKAGE_PIN W18 [get_ports {fmc_adda_data[10]}]
set_property PACKAGE_PIN Y19 [get_ports {fmc_adda_data[9]}]
set_property PACKAGE_PIN Y18 [get_ports {fmc_adda_data[8]}]
set_property PACKAGE_PIN V18 [get_ports {fmc_adda_data[7]}]
set_property PACKAGE_PIN V17 [get_ports {fmc_adda_data[6]}]
set_property PACKAGE_PIN Y16 [get_ports {fmc_adda_data[5]}]
set_property PACKAGE_PIN W16 [get_ports {fmc_adda_data[4]}]
set_property PACKAGE_PIN V12 [get_ports {fmc_adda_data[3]}]
set_property PACKAGE_PIN W13 [get_ports {fmc_adda_data[2]}]
set_property PACKAGE_PIN W14 [get_ports {fmc_adda_data[1]}]
set_property PACKAGE_PIN Y14 [get_ports {fmc_adda_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports fmc_clk  ]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_nl   ]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_nwait]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_nwe  ]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_ncs  ]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_noe  ]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_int  ]
set_property IOSTANDARD LVCMOS33 [get_ports mcu_int  ]

set_property PACKAGE_PIN T19 [get_ports fmc_clk  ]
set_property PACKAGE_PIN T12 [get_ports fmc_nl   ]
set_property PACKAGE_PIN P14 [get_ports fmc_nwait]
set_property PACKAGE_PIN R14 [get_ports fmc_nwe  ]
set_property PACKAGE_PIN U12 [get_ports fmc_ncs  ]
set_property PACKAGE_PIN U13 [get_ports fmc_noe  ]
set_property PACKAGE_PIN V15 [get_ports fmc_int  ]
set_property PACKAGE_PIN T11 [get_ports mcu_int  ]